spring.application.name=springApi
weather.api.base-url=https://api.openweathermap.org/data/2.5
weather.api.key=f6a2042d522bc1a72ff69acd7d36acbc
weather.api.timeout=5000
logging.level.org.springframework.web.reactive.function.client=DEBUG