spring.application.name=springApi
weather.api.base-url=https://api.openweathermap.org/data/2.5
weather.api.key="yourr key"
weather.api.timeout=5000
logging.level.org.springframework.web.reactive.function.client=DEBUG